[package]
name = "slack-scrabble-bot"
version = "0.1.0"
authors = ["Tyler Zhang <tztylerzhang@gmail.com>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
rocket_contrib = "*"

serde = "*"
serde_derive = "*"
serde_json = "*"
serde_urlencoded = "*"

uuid = { version = "*", features = ["serde", "v4"] }

failure = "*"
failure_derive = "*"

auto_impl = "*"
